package DBConnection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author ATaha
 */
public class DBHandler extends Configs {

    Connection dbConnection;

    public Connection getConnection() {
        // "jdbc:hsqldb:file:database/invdbfx;shutdown=true";
        String connectionString = "jdbc:hsqldb:file:database/invdbfx;shutdown=true";
        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            dbConnection = DriverManager.getConnection(connectionString, Configs.dbuser, Configs.dbpass);
            initializeDatabase();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return dbConnection;
    }

    private void initializeDatabase() {
        try (Statement stmt = dbConnection.createStatement()) {
            String createTableSQL = "CREATE TABLE IF NOT EXISTS youtubers (" +
                                    "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                                    "names VARCHAR(255) NOT NULL, " +
                                    "password VARCHAR(255) NOT NULL, " +
                                    "gender VARCHAR(50), " +
                                    "location VARCHAR(255))";
            stmt.executeUpdate(createTableSQL);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
